# Generated by Django 4.2.27 on 2025-12-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pociones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocionespedido',
            old_name='precio',
            new_name='precio_unidad',
        ),
        migrations.RemoveField(
            model_name='pocionespedido',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='pocionespedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
