# Generated by Django 4.2.27 on 2025-12-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pociones', '0002_rename_precio_pocionespedido_precio_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocion',
            name='ingredientes',
            field=models.ManyToManyField(to='pociones.ingrediente'),
        ),
        migrations.AlterField(
            model_name='pocionespedido',
            name='precio_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
